<a href="https://colab.research.google.com/github/umairahmed30/FCS_Project/blob/master/FCS_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
# Load the CSV file
file_path = 'data.csv'
data = pd.read_csv(file_path)

<ipython-input-4-98bfd988948c>:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

In [5]:
# Filter rows where trip_distance > 50
filtered_data = data[data['trip_distance'] > 50]

# Display the filtered data
# print(filtered_data)
filtered_data.head()

# # Optionally, save the filtered data to a new CSV file
# filtered_data.to_csv('filtered_data.csv', index=False)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
23842,2.0,2020-01-01 01:53:07,2020-01-01 03:54:41,1.0,52.30,5.0,N,262,265,1.0,300.0,0.0,0.0,61.78,6.12,0.3,370.70,2.5
39013,2.0,2020-01-01 02:05:07,2020-01-01 03:03:10,1.0,51.23,5.0,N,264,264,1.0,329.0,0.0,0.5,100.78,6.12,0.3,436.70,0.0
41620,1.0,2020-01-01 03:05:54,2020-01-01 04:16:26,1.0,53.80,5.0,N,132,265,1.0,250.0,0.0,0.0,53.35,16.62,0.3,320.27,0.0
58262,2.0,2020-01-01 05:36:12,2020-01-01 06:40:06,1.0,55.23,5.0,N,132,265,2.0,170.0,0.0,0.5,0.00,18.26,0.3,189.06,0.0
63024,2.0,2020-01-01 07:40:30,2020-01-01 08:40:01,1.0,54.19,5.0,N,132,265,1.0,230.0,0.0,0.0,0.00,12.24,0.3,242.54,0.0

In [3]:
# Filter rows where payment_type is missing
missing_payment_data = data[data['payment_type'].isna()]

missing_payment_data.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
6339567,NaN,2020-01-01 08:51:00,2020-01-01 09:19:00,NaN,13.69,NaN,NaN,136,232,NaN,51.05,2.75,0.5,0.0,0.00,0.3,54.60,0.0
6339568,NaN,2020-01-01 08:38:43,2020-01-01 08:51:08,NaN,3.42,NaN,NaN,121,9,NaN,27.06,2.75,0.0,0.0,0.00,0.3,30.11,0.0
6339569,NaN,2020-01-01 08:27:00,2020-01-01 08:32:00,NaN,2.20,NaN,NaN,197,216,NaN,24.36,2.75,0.5,0.0,0.00,0.3,27.91,0.0
6339570,NaN,2020-01-01 08:46:00,2020-01-01 08:57:00,NaN,0.84,NaN,NaN,262,236,NaN,26.08,2.75,0.5,0.0,0.00,0.3,29.63,0.0
6339571,NaN,2020-01-01 08:21:00,2020-01-01 08:38:00,NaN,7.24,NaN,NaN,45,142,NaN,25.28,2.75,0.5,0.0,0.00,0.3,28.83,0.0
6339572,NaN,2020-01-01 08:57:00,2020-01-01 09:09:00,NaN,1.67,NaN,NaN,35,61,NaN,16.23,2.75,0.5,0.0,0.00,0.3,19.78,0.0
6339573,NaN,2020-01-01 08:16:00,2020-01-01 08:30:00,NaN,10.04,NaN,NaN,182,238,NaN,34.06,2.75,0.5,0.0,0.00,0.3,37.61,0.0
6339574,NaN,2020-01-01 08:48:17,2020-01-01 09:11:52,NaN,4.45,NaN,NaN,17,35,NaN,26.73,2.75,0.0,0.0,0.00,0.3,29.78,0.0
6339575,NaN,2020-01-01 08:01:00,2020-01-01 08:27:00,NaN,12.66,NaN,NaN,117,130,NaN,37.96,2.75,0.5,0.0,2.29,0.3,43.80,0.0
6339576,NaN,2020-01-01 08:48:00,2020-01-01 09:10:25,NaN,15.14,NaN,NaN,81,215,NaN,46.92,2.75,0.0,0.0,6.12,0.3,56.09,0.0

In [4]:
# Group by (PULocationID, DOLocationID) and count the number of trips
trip_counts = data.groupby(['PULocationID', 'DOLocationID']).size().reset_index(name='trip_count')

# Display the result
trip_counts.head(10)

   PULocationID  DOLocationID  trip_count
0             1             1         638
1             1            50           1
2             1            68           1
3             1           138           2
4             1           140           1
5             1           148           1
6             1           211           1
7             1           231           1
8             1           264         105
9             1           265           4

In [5]:
# Identify rows with missing values in the specified columns
bad = data[data[['VendorID', 'passenger_count', 'store_and_fwd_flag', 'payment_type']].isna().any(axis=1)]

# Save the 'bad' DataFrame to a new CSV file
bad.to_csv('bad_data.csv', index=False)

# Remove the rows with missing values from the original DataFrame
data_cleaned = data.drop(bad.index)

# Save the cleaned data to a new CSV file (optional)
data_cleaned.to_csv('cleaned_data.csv', index=False)

In [6]:
# Ensure datetime columns are properly converted
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])
data['tpep_dropoff_datetime'] = pd.to_datetime(data['tpep_dropoff_datetime'])

# Calculate trip duration in minutes and store in a new column
data['duration'] = (data['tpep_dropoff_datetime'] - data['tpep_pickup_datetime']).dt.total_seconds() / 60

# Display the updated DataFrame with the new 'duration' column
print(data[['tpep_pickup_datetime', 'tpep_dropoff_datetime', 'duration']].head())

# Save the updated data to a new CSV file (optional)
data.to_csv('data_with_duration.csv', index=False)

  tpep_pickup_datetime tpep_dropoff_datetime  duration
0  2020-01-01 00:28:15   2020-01-01 00:33:03  4.800000
1  2020-01-01 00:35:39   2020-01-01 00:43:04  7.416667
2  2020-01-01 00:47:41   2020-01-01 00:53:52  6.183333
3  2020-01-01 00:55:23   2020-01-01 01:00:14  4.850000
4  2020-01-01 00:01:58   2020-01-01 00:04:16  2.300000

In [7]:
import pandas as pd

# Load the CSV file
file_path = 'data.csv'
data = pd.read_csv(file_path)

# Group by PULocationID and count the number of trips
pickup_counts = data.groupby('PULocationID').size().reset_index(name='trip_count')

# Display the result
print(pickup_counts)

# Optionally, save the result to a new CSV file
pickup_counts.to_csv('pickup_counts.csv', index=False)

<ipython-input-7-b4c25acb392b>:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)

     PULocationID  trip_count
0               1         755
1               2           3
2               3         206
3               4       10147
4               5          39
..            ...         ...
256           261       34583
257           262       85805
258           263      124733
259           264       43958
260           265        3160

[261 rows x 2 columns]

In [8]:
# Ensure tpep_pickup_datetime is in datetime format
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

# Group trips into 30-minute intervals and count the number of trips per interval
interval_counts = data.groupby('pickup_interval').size().reset_index(name='trip_count')

# Display the intervals and their trip counts
print(interval_counts)

# Optionally, save the results to a CSV file
interval_counts.to_csv('interval_trip_counts.csv', index=False)

<ipython-input-8-a55d0a1e322b>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

         pickup_interval  trip_count
0    2003-01-01 00:00:00           1
1    2008-12-31 23:00:00           7
2    2008-12-31 23:30:00           3
3    2009-01-01 00:00:00           9
4    2009-01-01 00:30:00           4
...                  ...         ...
1534 2020-07-10 11:30:00           1
1535 2020-07-31 18:30:00           1
1536 2021-01-02 00:00:00           1
1537 2021-01-02 00:30:00           1
1538 2021-01-02 01:00:00           1

[1539 rows x 2 columns]

In [9]:
# Ensure tpep_pickup_datetime is in datetime format
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

# Group by pickup_interval and calculate averages
interval_stats = data.groupby('pickup_interval').agg(
    average_passengers=('passenger_count', 'mean'),
    average_fare=('fare_amount', 'mean')
).reset_index()

# Display the results
print(interval_stats)

# Optionally, save the results to a CSV file
interval_stats.to_csv('interval_stats.csv', index=False)

<ipython-input-9-edff37f963df>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

         pickup_interval  average_passengers  average_fare
0    2003-01-01 00:00:00            1.000000      0.000000
1    2008-12-31 23:00:00            2.000000     18.857143
2    2008-12-31 23:30:00            1.000000     22.666667
3    2009-01-01 00:00:00            1.777778     25.166667
4    2009-01-01 00:30:00            2.000000     24.250000
...                  ...                 ...           ...
1534 2020-07-10 11:30:00            1.000000      7.000000
1535 2020-07-31 18:30:00            1.000000      5.000000
1536 2021-01-02 00:00:00            1.000000     10.500000
1537 2021-01-02 00:30:00            1.000000     11.500000
1538 2021-01-02 01:00:00            1.000000     10.000000

[1539 rows x 3 columns]

In [5]:
# Ensure tpep_pickup_datetime is in datetime format
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

# Group by pickup_interval and payment_type, and calculate the average fare amount
interval_payment_stats = data.groupby(['pickup_interval', 'payment_type']).agg(
    average_fare=('fare_amount', 'mean')
).reset_index()

# Display the results
print(interval_payment_stats)

# Optionally, save the results to a CSV file
interval_payment_stats.to_csv('interval_payment_stats.csv', index=False)

<ipython-input-5-8ea1e016f296>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

         pickup_interval  payment_type  average_fare
0    2003-01-01 00:00:00           2.0           0.0
1    2008-12-31 23:00:00           1.0          13.5
2    2008-12-31 23:00:00           2.0          26.0
3    2008-12-31 23:30:00           1.0          52.0
4    2008-12-31 23:30:00           2.0           8.0
...                  ...           ...           ...
6007 2020-07-10 11:30:00           1.0           7.0
6008 2020-07-31 18:30:00           2.0           5.0
6009 2021-01-02 00:00:00           2.0          10.5
6010 2021-01-02 00:30:00           2.0          11.5
6011 2021-01-02 01:00:00           1.0          10.0

[6012 rows x 3 columns]

In [6]:
# Ensure tpep_pickup_datetime is in datetime format
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

# Group by pickup_interval and payment_type, and calculate the average fare amount
interval_payment_stats = data.groupby(['pickup_interval', 'payment_type']).agg(
    average_fare=('fare_amount', 'mean')
).reset_index()

# Find the interval with the maximum average fare for each payment type
max_fare_intervals = interval_payment_stats.loc[
    interval_payment_stats.groupby('payment_type')['average_fare'].idxmax()
].reset_index(drop=True)

# Display the results
print(max_fare_intervals)

# Optionally, save the results to a CSV file
max_fare_intervals.to_csv('max_fare_intervals.csv', index=False)

<ipython-input-6-af0ee7626637>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

      pickup_interval  payment_type  average_fare
0 2008-12-31 23:30:00           1.0       52.0000
1 2009-01-01 00:00:00           2.0       26.4375
2 2020-01-16 03:30:00           3.0       45.8000
3 2020-01-23 05:00:00           4.0       83.8000
4 2020-01-21 17:30:00           5.0        0.0000

In [7]:

# Ensure tpep_pickup_datetime is in datetime format
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')

# Calculate the tip-to-fare ratio (avoid division by zero)
data['tip_to_fare_ratio'] = data['tip_amount'] / data['fare_amount']
data['tip_to_fare_ratio'].fillna(0, inplace=True)  # Handle NaN values
data['tip_to_fare_ratio'].replace([float('inf'), -float('inf')], 0, inplace=True)

# Group by pickup_interval and payment_type to calculate the average tip-to-fare ratio
interval_tip_stats = data.groupby(['pickup_interval', 'payment_type']).agg(
    average_tip_to_fare_ratio=('tip_to_fare_ratio', 'mean')
).reset_index()

# Find the interval with the maximum average tip-to-fare ratio for each payment type
max_tip_fare_intervals = interval_tip_stats.loc[
    interval_tip_stats.groupby('payment_type')['average_tip_to_fare_ratio'].idxmax()
].reset_index(drop=True)

# Display the results
print(max_tip_fare_intervals)

# Optionally, save the results to a CSV file
max_tip_fare_intervals.to_csv('max_tip_fare_intervals.csv', index=False)

<ipython-input-7-9100dff9ffd5>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  data['pickup_interval'] = data['tpep_pickup_datetime'].dt.floor('30T')
<ipython-input-7-9100dff9ffd5>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['tip_to_fare_ratio'].fillna(0, inplace=True)  # Handle NaN values
<ipython-input-7-9100dff9ffd5>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['tip_to_fare_ratio'].replace([float('inf'), -float('inf')], 0, inplace=True)

      pickup_interval  payment_type  average_tip_to_fare_ratio
0 2020-01-07 01:30:00           1.0                  26.446845
1 2020-01-29 09:00:00           2.0                   0.001158
2 2020-01-01 21:00:00           3.0                   1.066667
3 2020-01-27 17:00:00           4.0                   0.240000
4 2020-01-21 17:30:00           5.0                   0.000000

In [8]:
# Group by PULocationID to calculate the average fare amount
pickup_fare_stats = data.groupby('PULocationID').agg(
    average_fare=('fare_amount', 'mean')
).reset_index()

# Find the PULocationID with the highest average fare amount
highest_pickup_location = pickup_fare_stats.loc[
    pickup_fare_stats['average_fare'].idxmax()
]

# Group by DOLocationID to calculate the average fare amount
dropoff_fare_stats = data.groupby('DOLocationID').agg(
    average_fare=('fare_amount', 'mean')
).reset_index()

# Find the DOLocationID with the highest average fare amount
highest_dropoff_location = dropoff_fare_stats.loc[
    dropoff_fare_stats['average_fare'].idxmax()
]

# Display the results
print("Highest Pickup Location:")
print(highest_pickup_location)
print("\nHighest Dropoff Location:")
print(highest_dropoff_location)

# Optionally, save the results to a CSV file
pickup_fare_stats.to_csv('pickup_fare_stats.csv', index=False)
dropoff_fare_stats.to_csv('dropoff_fare_stats.csv', index=False)

Highest Pickup Location:
PULocationID    204.0
average_fare    107.0
Name: 199, dtype: float64

Highest Dropoff Location:
DOLocationID    44.000000
average_fare    85.548971
Name: 43, dtype: float64

In [9]:
# Determine the 5 most common destinations for each pickup location
top_destinations = (
    data.groupby(['PULocationID', 'DOLocationID'])
    .size()
    .reset_index(name='trip_count')
    .sort_values(['PULocationID', 'trip_count'], ascending=[True, False])
    .groupby('PULocationID')
    .head(5)
)

# Filter the original data to keep only trips to the top 5 destinations for each pickup location
common = data.merge(
    top_destinations[['PULocationID', 'DOLocationID']],
    on=['PULocationID', 'DOLocationID']
)

# Display the resulting DataFrame
print(common)

# Optionally, save the resulting DataFrame to a CSV file
common.to_csv('common_trips.csv', index=False)

         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0             1.0  2020-01-01 00:28:15   2020-01-01 00:33:03              1.0
1             1.0  2020-01-01 00:35:39   2020-01-01 00:43:04              1.0
2             1.0  2020-01-01 00:47:41   2020-01-01 00:53:52              1.0
3             1.0  2020-01-01 00:55:23   2020-01-01 01:00:14              1.0
4             2.0  2020-01-01 00:01:58   2020-01-01 00:04:16              1.0
...           ...                  ...                   ...              ...
1964557       NaN  2020-01-31 06:41:00   2020-01-31 07:17:00              NaN
1964558       NaN  2020-01-31 06:04:00   2020-01-31 06:07:00              NaN
1964559       NaN  2020-01-31 06:06:57   2020-01-31 06:57:15              NaN
1964560       NaN  2020-01-31 21:14:39   2020-01-31 21:18:38              NaN
1964561       NaN  2020-01-31 21:46:00   2020-01-31 21:53:00              NaN

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 1.20         1.0                  N           238
1                 1.20         1.0                  N           239
2                 0.60         1.0                  N           238
3                 0.80         1.0                  N           238
4                 0.00         1.0                  N           193
...                ...         ...                ...           ...
1964557          12.08         NaN                NaN            32
1964558           0.15         NaN                NaN            81
1964559          19.76         NaN                NaN           191
1964560           0.41         NaN                NaN           143
1964561           0.79         NaN                NaN           263

         DOLocationID  payment_type  fare_amount  extra  mta_tax  tip_amount  \
0                 239           1.0         6.00   3.00      0.5        1.47
1                 238           1.0         7.00   3.00      0.5        1.50
2                 238           1.0         6.00   3.00      0.5        1.00
3                 151           1.0         5.50   0.50      0.5        1.36
4                 193           2.0         3.50   0.50      0.5        0.00
...               ...           ...          ...    ...      ...         ...
1964557           145           NaN        34.92   2.75      0.5        0.00
1964558            51           NaN        30.66   2.75      0.5        0.00
1964559           261           NaN        58.50   2.75      0.0        0.00
1964560           143           NaN        13.88   5.50      0.5        0.00
1964561           263           NaN        26.08   2.75      0.5        0.00

         tolls_amount  improvement_surcharge  total_amount  \
0                0.00                    0.3         11.27
1                0.00                    0.3         12.30
2                0.00                    0.3         10.80
3                0.00                    0.3          8.16
4                0.00                    0.3          4.80
...               ...                    ...           ...
1964557          6.12                    0.3         44.59
1964558          0.00                    0.3         34.21
1964559          0.00                    0.3         61.55
1964560          0.00                    0.3         20.18
1964561          0.00                    0.3         29.63

         congestion_surcharge     pickup_interval  tip_to_fare_ratio
0                         2.5 2020-01-01 00:00:00           0.245000
1                         2.5 2020-01-01 00:30:00           0.214286
2                         2.5 2020-01-01 00:30:00           0.166667
3                         0.0 2020-01-01 00:30:00           0.247273
4                         0.0 2020-01-01 00:00:00           0.000000
...                       ...                 ...                ...
1964557                   0.0 2020-01-31 06:30:00           0.000000
1964558                   0.0 2020-01-31 06:00:00           0.000000
1964559                   0.0 2020-01-31 06:00:00           0.000000
1964560                   0.0 2020-01-31 21:00:00           0.000000
1964561                   0.0 2020-01-31 21:30:00           0.000000

[1964562 rows x 20 columns]

In [10]:
# Ensure the tpep_pickup_datetime column is in datetime format
common['tpep_pickup_datetime'] = pd.to_datetime(common['tpep_pickup_datetime'])

# Round down to the nearest 30-minute interval
common['pickup_interval'] = common['tpep_pickup_datetime'].dt.floor('30T')

# Group by payment type and interval to calculate the average fare amount
average_fare_by_payment_and_interval = (
    common.groupby(['payment_type', 'pickup_interval'])
    .agg(average_fare=('fare_amount', 'mean'))
    .reset_index()
)

# Display the results
print(average_fare_by_payment_and_interval)

# Optionally, save the results to a CSV file
average_fare_by_payment_and_interval.to_csv('average_fare_by_payment_and_interval.csv', index=False)

      payment_type     pickup_interval  average_fare
0              1.0 2008-12-31 23:00:00      6.000000
1              1.0 2019-12-18 15:00:00      0.010000
2              1.0 2019-12-18 15:30:00      2.500000
3              1.0 2019-12-31 14:00:00      6.000000
4              1.0 2019-12-31 16:30:00      7.000000
...            ...                 ...           ...
5891           4.0 2020-01-31 22:00:00      1.187500
5892           4.0 2020-01-31 22:30:00      8.800000
5893           4.0 2020-01-31 23:00:00     -1.833333
5894           4.0 2020-01-31 23:30:00    -16.437500
5895           5.0 2020-01-21 17:30:00      0.000000

[5896 rows x 3 columns]

<ipython-input-10-787132517e52>:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  common['pickup_interval'] = common['tpep_pickup_datetime'].dt.floor('30T')

In [11]:
# Assuming 'average_fare_by_payment_and_interval' is the DataFrame for the 'common' DataFrame
# Assuming 'interval_payment_stats' is the DataFrame with the pre-computed stats

# Merge the two DataFrames on 'payment_type' and 'pickup_interval'
merged_stats = pd.merge(
    average_fare_by_payment_and_interval,
    interval_payment_stats,
    on=['payment_type', 'pickup_interval'],
    suffixes=('_common', '_overall')
)

# Compute the difference
merged_stats['fare_diff'] = (
    merged_stats['average_fare_common'] - merged_stats['average_fare_overall']
)

# Display the resulting DataFrame
print(merged_stats)

# Optionally, save the results to a CSV file
merged_stats.to_csv('fare_difference_stats.csv', index=False)

      payment_type     pickup_interval  average_fare_common  \
0              1.0 2008-12-31 23:00:00             6.000000
1              1.0 2019-12-18 15:00:00             0.010000
2              1.0 2019-12-18 15:30:00             2.500000
3              1.0 2019-12-31 14:00:00             6.000000
4              1.0 2019-12-31 16:30:00             7.000000
...            ...                 ...                  ...
5891           4.0 2020-01-31 22:00:00             1.187500
5892           4.0 2020-01-31 22:30:00             8.800000
5893           4.0 2020-01-31 23:00:00            -1.833333
5894           4.0 2020-01-31 23:30:00           -16.437500
5895           5.0 2020-01-21 17:30:00             0.000000

      average_fare_overall  fare_diff
0                13.500000  -7.500000
1                 0.010000   0.000000
2                 2.500000   0.000000
3                12.750000  -6.750000
4                 7.000000   0.000000
...                    ...        ...
5891             -1.000000   2.187500
5892              6.605263   2.194737
5893             -1.425926  -0.407407
5894             -7.111111  -9.326389
5895              0.000000   0.000000

[5896 rows x 5 columns]

In [12]:
# Ensure the previous merge is available as `merged_stats`

# Compute the ratio
merged_stats['fare_ratio'] = merged_stats['fare_diff'] / merged_stats['average_fare_overall']

# Display the resulting DataFrame
print(merged_stats)

# Optionally, save the results to a CSV file
merged_stats.to_csv('fare_ratio_stats.csv', index=False)

      payment_type     pickup_interval  average_fare_common  \
0              1.0 2008-12-31 23:00:00             6.000000
1              1.0 2019-12-18 15:00:00             0.010000
2              1.0 2019-12-18 15:30:00             2.500000
3              1.0 2019-12-31 14:00:00             6.000000
4              1.0 2019-12-31 16:30:00             7.000000
...            ...                 ...                  ...
5891           4.0 2020-01-31 22:00:00             1.187500
5892           4.0 2020-01-31 22:30:00             8.800000
5893           4.0 2020-01-31 23:00:00            -1.833333
5894           4.0 2020-01-31 23:30:00           -16.437500
5895           5.0 2020-01-21 17:30:00             0.000000

      average_fare_overall  fare_diff  fare_ratio
0                13.500000  -7.500000   -0.555556
1                 0.010000   0.000000    0.000000
2                 2.500000   0.000000    0.000000
3                12.750000  -6.750000   -0.529412
4                 7.000000   0.000000    0.000000
...                    ...        ...         ...
5891             -1.000000   2.187500   -2.187500
5892              6.605263   2.194737    0.332271
5893             -1.425926  -0.407407    0.285714
5894             -7.111111  -9.326389    1.311523
5895              0.000000   0.000000         NaN

[5896 rows x 6 columns]

In [13]:
# Convert datetime columns to datetime objects
data['tpep_pickup_datetime'] = pd.to_datetime(data['tpep_pickup_datetime'])
data['tpep_dropoff_datetime'] = pd.to_datetime(data['tpep_dropoff_datetime'])

# Sort the data by VendorID, tpep_dropoff_datetime, and PULocationID
data = data.sort_values(by=['VendorID', 'tpep_dropoff_datetime', 'PULocationID']).reset_index(drop=True)

# Initialize a 'chain' column with unique IDs
data['chain'] = range(len(data))

# Iterate through rows to find consecutive trips
for i in range(1, len(data)):
    current = data.iloc[i]
    previous = data.iloc[i - 1]

    if (
        current['VendorID'] == previous['VendorID'] and  # Same VendorID
        current['PULocationID'] == previous['DOLocationID'] and  # Matching locations
        current['tpep_pickup_datetime'] > previous['tpep_dropoff_datetime'] and  # Pickup after dropoff
        (current['tpep_pickup_datetime'] - previous['tpep_dropoff_datetime']).total_seconds() <= 120  # Within 2 minutes
    ):
        # Assign the same chain ID
        data.loc[i, 'chain'] = data.loc[i - 1, 'chain']

# Display the dataset with the 'chain' column
print(data)

# Save the result to a CSV file
data.to_csv('trip_chains.csv', index=False)

         VendorID tpep_pickup_datetime tpep_dropoff_datetime  passenger_count  \
0             1.0  2020-01-01 00:01:40   2020-01-01 00:01:52              1.0
1             1.0  2020-01-01 00:00:50   2020-01-01 00:02:32              2.0
2             1.0  2020-01-01 00:00:07   2020-01-01 00:03:26              3.0
3             1.0  2020-01-01 00:01:55   2020-01-01 00:04:34              2.0
4             1.0  2020-01-01 00:01:01   2020-01-01 00:04:46              1.0
...           ...                  ...                   ...              ...
6405003       NaN  2020-01-31 23:42:00   2020-02-01 00:18:00              NaN
6405004       NaN  2020-01-31 23:56:00   2020-02-01 00:20:00              NaN
6405005       NaN  2020-01-31 23:44:33   2020-02-01 00:26:52              NaN
6405006       NaN  2020-01-31 23:54:00   2020-02-01 00:33:00              NaN
6405007       NaN  2020-01-31 23:47:00   2020-02-01 00:39:00              NaN

         trip_distance  RatecodeID store_and_fwd_flag  PULocationID  \
0                 0.00         2.0                  N            79
1                 0.30         1.0                  N           158
2                 0.60         1.0                  N            75
3                 1.00         1.0                  N           141
4                 0.50         1.0                  N           236
...                ...         ...                ...           ...
6405003          10.64         NaN                NaN           114
6405004           5.31         NaN                NaN            17
6405005          16.74         NaN                NaN           143
6405006          10.61         NaN                NaN            48
6405007          14.52         NaN                NaN            89

         DOLocationID  payment_type  ...  extra  mta_tax  tip_amount  \
0                  79           1.0  ...   2.50      0.5       12.25
1                 158           2.0  ...   3.00      0.5        0.00
2                  75           2.0  ...   0.50      0.5        0.00
3                 140           1.0  ...   3.00      0.5        1.75
4                 236           2.0  ...   3.00      0.5        0.00
...               ...           ...  ...    ...      ...         ...
6405003            22           NaN  ...   2.75      0.5        0.00
6405004            76           NaN  ...   2.75      0.5        0.00
6405005            85           NaN  ...   5.50      0.0        0.00
6405006            47           NaN  ...   2.75      0.5        0.00
6405007            83           NaN  ...   2.75      0.5        0.00

         tolls_amount  improvement_surcharge  total_amount  \
0                6.12                    0.3         73.67
1                0.00                    0.3          7.30
2                0.00                    0.3          5.80
3                0.00                    0.3         10.55
4                0.00                    0.3          8.30
...               ...                    ...           ...
6405003          0.00                    0.3         49.20
6405004          0.00                    0.3         29.88
6405005          6.12                    0.3         57.30
6405006          0.00                    0.3         48.21
6405007          0.00                    0.3         44.35

         congestion_surcharge     pickup_interval tip_to_fare_ratio    chain
0                         2.5 2020-01-01 00:00:00          0.235577        0
1                         2.5 2020-01-01 00:00:00          0.000000        1
2                         0.0 2020-01-01 00:00:00          0.000000        2
3                         2.5 2020-01-01 00:00:00          0.350000        3
4                         2.5 2020-01-01 00:00:00          0.000000        4
...                       ...                 ...               ...      ...
6405003                   0.0 2020-01-31 23:30:00          0.000000  6405003
6405004                   0.0 2020-01-31 23:30:00          0.000000  6405004
6405005                   0.0 2020-01-31 23:30:00          0.000000  6405005
6405006                   0.0 2020-01-31 23:30:00          0.000000  6405006
6405007                   0.0 2020-01-31 23:30:00          0.000000  6405007

[6405008 rows x 21 columns]